### ISSUE TITLE
TODO: add/configure tests

### ISSUE THREAD

**Issue by webknjaz** [webknjaz/ansible-gentoo-laptop#1]
* [ ] https://github.com/willthames/ansible-lint
* [ ] https://kitchen.ci/docs/getting-started/ / https://readme.fr/continuous-integration-for-ansible/
* [ ] https://molecule.readthedocs.io/en/latest/
